--------------------------------------------------------
-- Archivo creado  - s�bado-agosto-03-2019
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------
CREATE TABLE "SYSTEM"."CATEGORIA" (
  "NOMBRE" VARCHAR2(200 BYTE),
  "NOMBRE_CORTO" VARCHAR2(15 BYTE),
  "ESTADO" CHAR(1 BYTE)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "SYSTEM";
REM INSERTING into SYSTEM.CATEGORIA
SET
  DEFINE OFF;
Insert into
  SYSTEM.CATEGORIA (NOMBRE, NOMBRE_CORTO, ESTADO)
values
  ('HERRAMIENTA', 'HE', '1');
--------------------------------------------------------
  --  DDL for Index SYS_C007016
  --------------------------------------------------------
  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007016" ON "SYSTEM"."CATEGORIA" ("NOMBRE") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "SYSTEM";
--------------------------------------------------------
  --  Constraints for Table CATEGORIA
  --------------------------------------------------------
ALTER TABLE
  "SYSTEM"."CATEGORIA"
ADD
  PRIMARY KEY ("NOMBRE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "SYSTEM" ENABLE;
ALTER TABLE
  "SYSTEM"."CATEGORIA"
MODIFY
  ("NOMBRE" NOT NULL ENABLE);