--------------------------------------------------------
-- Archivo creado  - s�bado-agosto-03-2019
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------
CREATE TABLE "SYSTEM"."PROVEEDOR" (
  "EMPR_REPR" VARCHAR2(255 BYTE),
  "CLIENTE" VARCHAR2(13 BYTE)
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "SYSTEM";
REM INSERTING into SYSTEM.PROVEEDOR
SET
  DEFINE OFF;
Insert into
  SYSTEM.PROVEEDOR (EMPR_REPR, CLIENTE)
values
  ('BLACK AND DECKER', '0702636150');
--------------------------------------------------------
  --  DDL for Index SYS_C007012
  --------------------------------------------------------
  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007012" ON "SYSTEM"."PROVEEDOR" ("EMPR_REPR") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "SYSTEM";
--------------------------------------------------------
  --  Constraints for Table PROVEEDOR
  --------------------------------------------------------
ALTER TABLE
  "SYSTEM"."PROVEEDOR"
ADD
  PRIMARY KEY ("EMPR_REPR") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "SYSTEM" ENABLE;
ALTER TABLE
  "SYSTEM"."PROVEEDOR"
MODIFY
  ("EMPR_REPR" NOT NULL ENABLE);