--------------------------------------------------------
-- Archivo creado  - sábado-agosto-03-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DETALLE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."DETALLE" 
   (	"ID" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"PRECIO" NUMBER(*,2), 
	"PRODUCTO" VARCHAR2(50 BYTE), 
	"FACTURA" NUMBER(*,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.DETALLE
SET DEFINE OFF;
Insert into SYSTEM.DETALLE (ID,CANTIDAD,PRECIO,PRODUCTO,FACTURA) values ('1','1','99,99','001','1');
--------------------------------------------------------
--  DDL for Index SYS_C007030
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007030" ON "SYSTEM"."DETALLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table DETALLE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."DETALLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."DETALLE" MODIFY ("ID" NOT NULL ENABLE);
