--------------------------------------------------------
-- Archivo creado  - s�bado-agosto-03-2019
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------
CREATE TABLE "SYSTEM"."FACTURA" (
  "ID" NUMBER(*, 0),
  "CLIENTE" VARCHAR2(13 BYTE),
  "IVA" NUMBER(*, 2),
  "DESCUENTO" NUMBER(*, 2),
  "SUBTOTAL" NUMBER(*, 2),
  "TOTAL" NUMBER(*, 2),
  "ESTADO" CHAR(1 BYTE),
  "FORMA_DE_PAGO" NUMBER(*, 0),
  "FECHA" DATE
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "SYSTEM";
REM INSERTING into SYSTEM.FACTURA
SET
  DEFINE OFF;
Insert into
  SYSTEM.FACTURA (
    ID,
    CLIENTE,
    IVA,
    DESCUENTO,
    SUBTOTAL,
    TOTAL,
    ESTADO,
    FORMA_DE_PAGO,
    FECHA
  )
values
  (
    '1',
    '0702636150',
    '11,99',
    '0',
    '99,99',
    '111,98',
    '1',
    '1',
    to_date('28/07/2019', 'DD/MM/RRRR')
  );
--------------------------------------------------------
  --  DDL for Index SYS_C007020
  --------------------------------------------------------
  CREATE UNIQUE INDEX "SYSTEM"."SYS_C007020" ON "SYSTEM"."FACTURA" ("ID") PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "SYSTEM";
--------------------------------------------------------
  --  Constraints for Table FACTURA
  --------------------------------------------------------
ALTER TABLE
  "SYSTEM"."FACTURA"
ADD
  PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "SYSTEM" ENABLE;
ALTER TABLE
  "SYSTEM"."FACTURA"
MODIFY
  ("ID" NOT NULL ENABLE);
